CPP_FILES := $(wildcard *.cc)
OBJ_FILES := $(CPP_FILES:.c=.o)
LD_FLAGS := -std=c++11
CC_FLAGS := -D_JUDGE_ -D_GLIBCXX_DEBUG -ansi -O2 -Wall -Wextra -Wno-uninitialized -Wno-sign-compare -std=c++11

program.exe: $(OBJ_FILES)
	g++ $(LD_FLAGS) -o $@ $^

%.o: %.cpp
	g++ $(CC_FLAGS) -c -o $@ $