CPP_FILES := $(wildcard *.cc)
OBJ_FILES := $(CPP_FILES:.c=.o)
LD_FLAGS := -std=c++11 -O2
CC_FLAGS := -std=c++11 -O2

program.exe: $(OBJ_FILES)
	g++ $(LD_FLAGS) -o $@ $^

%.o: %.cpp
	g++ $(CC_FLAGS) -c -o $@ $